### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by 2892931976** [FreddyChen/NettyChat#15]
2020-03-28 18:32:14.538 2601-2628/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: com.example.msmk.nettychat, PID: 2601
    java.lang.IllegalStateException: app not init...
        at com.example.msmk.nettychat.NettyChatApp.sharedInstance(NettyChatApp.java:22)
        at com.example.msmk.nettychat.im.IMSEventListener.isNetworkAvailable(IMSEventListener.java:52)
        at com.example.msmk.imlib.netty.NettyTcpClient.isNetworkAvailable(NettyTcpClient.java:594)

**Comment by 2892931976** [comment]
public static NettyChatApp sharedInstance() {
        if (instance == null) {
            throw new IllegalStateException("app not init...");
        }
        return instance;
    }

**Comment by FreddyChen** [comment]
> 2020-03-28 18:32:14.538 2601-2628/? E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
> Process: com.example.msmk.nettychat, PID: 2601
> java.lang.IllegalStateException: app not init...
> at com.example.msmk.nettychat.NettyChatApp.sharedInstance(NettyChatApp.java:22)
> at com.example.msmk.nettychat.im.IMSEventListener.isNetworkAvailable(IMSEventListener.java:52)
> at com.example.msmk.imlib.netty.NettyTcpClient.isNetworkAvailable(NettyTcpClient.java:594)

这是application未初始化导致的，在AndroidManifest.xml指定一下就好了

**Comment by 2892931976** [comment]
好的，谢谢，以解决

**Comment by FreddyChen** [comment]
> 好的，谢谢，以解决

后期会出来一个比较完善的sdk，包括android客户端和java服务端，敬请期待。
